---
- name: Play for Install Nginx on WebServers
  hosts: localhost
  gather_facts: yes
  vars:
    custom_heading: "Welcome To Autoscaling Testing by Hariharan Bhuvanendhiran"
    todays_date: "{{ ansible_facts['date_time']['date'] }}"
    host_name: "{{ ansible_facts['hostname'] }}"
    fqdn_name: "{{ ansible_facts['fqdn'] }}"
    ip_address: "{{ ansible_facts['eth0']['ipv4']['address'] }}"
  tasks:
    - name: Run Apt Update
      shell: apt update && apt install -y python3-apt

    - name: Install Nginx Server
      apt:
        name: nginx
        state: present

    - name: Copy the custom index page (Jinja2 template)
      template:
        src: /myrepo/index.j2
        dest: /var/www/html/index.html  # Changed here
        owner: root
        group: root
        mode: '0644'

    - name: Copy the style file to destination folder
      copy:
        src: /myrepo/style.css
        dest: /var/www/html/style.css
        owner: root
        group: root
        mode: '0644'

    - name: Copy the JavaScript file to destination folder
      copy:
        src: /myrepo/scorekeeper.js
        dest: /var/www/html/scorekeeper.js
        owner: root
        group: root
        mode: '0644'

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
